"""empty message

Revision ID: 10ac8da502b5
Revises: 695de0c6cdf2
Create Date: 2019-12-16 21:15:34.537745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10ac8da502b5'
down_revision = '695de0c6cdf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('name',
    sa.Column('num', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('num'),
    sa.UniqueConstraint('num')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('name')
    # ### end Alembic commands ###
