"""empty message

Revision ID: 56c9ea130da0
Revises: 2f3bc7455bab
Create Date: 2019-12-16 21:19:50.042576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56c9ea130da0'
down_revision = '2f3bc7455bab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('worker_ibfk_1', 'worker', type_='foreignkey')
    op.create_foreign_key(None, 'worker', 'workshop', ['workshop_id'], ['workshop_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'worker', type_='foreignkey')
    op.create_foreign_key('worker_ibfk_1', 'worker', 'workshop', ['workshop_id'], ['workshop_id'], ondelete='CASCADE')
    # ### end Alembic commands ###
