"""empty message

Revision ID: 695de0c6cdf2
Revises: a91f6301db97
Create Date: 2019-12-16 21:14:50.290755

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '695de0c6cdf2'
down_revision = 'a91f6301db97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('num', table_name='name')
    op.drop_table('name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('name',
    sa.Column('num', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('num'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('num', 'name', ['num'], unique=True)
    # ### end Alembic commands ###
