"""empty message

Revision ID: a08efe7b534b
Revises: 38ccb7a4fb3a
Create Date: 2019-12-16 21:06:52.036360

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a08efe7b534b'
down_revision = '38ccb7a4fb3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('num', table_name='name')
    op.drop_table('name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('name',
    sa.Column('num', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('num'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('num', 'name', ['num'], unique=True)
    # ### end Alembic commands ###
