"""empty message

Revision ID: b1232e5387b4
Revises: eef1285271fb
Create Date: 2019-12-16 21:00:50.611887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1232e5387b4'
down_revision = 'eef1285271fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('worker_ibfk_1', 'worker', type_='foreignkey')
    op.create_foreign_key(None, 'worker', 'workshop', ['workshop_id'], ['workshop_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'worker', type_='foreignkey')
    op.create_foreign_key('worker_ibfk_1', 'worker', 'workshop', ['workshop_id'], ['workshop_id'])
    # ### end Alembic commands ###
