"""empty message

Revision ID: e9f983bf8dba
Revises: c7a8fcb1124f
Create Date: 2019-12-16 20:58:13.899132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9f983bf8dba'
down_revision = 'c7a8fcb1124f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('name',
    sa.Column('num', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('num'),
    sa.UniqueConstraint('num')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('name')
    # ### end Alembic commands ###
